import {inject} from 'aurelia-dependency-injection';
import {customAttribute} from 'aurelia-templating';
import {DOM} from 'aurelia-pal';

/**
 * `am-uuid` attribute used by `View` class to select an internal element generated by a component/template
 */
@customAttribute('am-uuid')
@inject(DOM.Element)
export class UuidAttribute {
    /**
     * Creates a new instance of Hide.
     * @param element Target element to conditionally hide. DOM.
     */
    constructor(element) {
        this.element = element;
    }
    /**
     *
     */
    bind() {
        this.element.setAttribute('am-uuid', this.value);
    }
    /**
     * Value Change Event
     * @param  {String}   newValue
     * @param  {String}   oldValue
     * @return {void}
     */
    valueChanged(newValue, oldValue) {
        this.element.style.backgroundColor = newValue;
    }
}
